### ISSUE TITLE
Image links in ConversionToAddressables.md broken

### ISSUE THREAD

**Issue by SimonDarksideJ** [oculus-samples/Unity-AssetStreaming#1]
Seems none of the images referenced in the following article are accessible or working.

https://github.com/oculus-samples/Unity-AssetStreaming/blob/main/ConversionToAddressables.md

**Comment by AlexThiv** [comment]
Thanks for raising this issue. We fixed the images on the page.

**Comment by SimonDarksideJ** [comment]
Thanks for responding so quickly @AlexThiv  :D
