### ISSUE TITLE
Oculus Package has been modified in this sample

### ISSUE THREAD

**Issue by SimonDarksideJ** [oculus-samples/Unity-AssetStreaming#3]
After cloning the project I updated the Oculus Integration package to the latest for testing, only to find one of the existing scripts in the Oculus Package had been edited by this sample, namely:

https://github.com/oculus-samples/Unity-AssetStreaming/blob/441e743c7a68ea4ad303f6ad28e244c1732aaf11/Assets/Oculus/SampleFramework/Core/Locomotion/Scripts/SimpleCapsuleWithStickMovement.cs#L9

Can a new script be created in this sample to re-introduce the changed script as no sample should modify packages provided by a vendor on an asset store.  This will prevent issues from developers testing this sample with newer versions of the dependencies (such as the Oculus Integration package)

**Comment by AlexThiv** [comment]
Thanks for raising this as an issue. 

We are working on updating the project to reduce friction with updates to latest Oculus Integration Package.

**Comment by AlexThiv** [comment]
We separated the samples used by the project from the ones provided in Oculus Integration. We also removed all features from Oculus Integration that were not needed by the project. The Readme has some additional details about how we used the Oculus Integration package.

We are going to close this issue.

Thanks for informing us of this issue and helping us make this project better and easier to use.

**Comment by SimonDarksideJ** [comment]
Fantastic stuff, great to see this sort of reaction on the repo 👍
