### ISSUE TITLE
LODGeneratorEditor.cs is not fully functioned

### ISSUE THREAD

**Issue by gcj2450** [oculus-samples/Unity-AssetStreaming#5]
LODGeneratorEditor.cs is not funtioned , there is some code removed , could i have the full code of LODGeneratorEditor.cs?

**Comment by pr0-zac** [comment]
It requires the Mesh Baker plugin which was not included for license reasons. [Further details are in the README.md.](https://ghe.oculus-rep.com/DevTech/Unity-AssetStreaming#third-party-libraries)
