### ISSUE TITLE
App hangs after splash screens

### ISSUE THREAD

**Issue by Ulthien** [oculus-samples/Unity-AssetStreaming#9]
Hello,

the project builds after one sets it to android platform, and the .apk starts on meta pro with both splashes and then hangs.
I assume some "other" settings for the build need be set properly for the target device - but these are not mentioned here & i I forgot the details after abstaining from Unity for the last 2 years...

pls help to get it running?

**Comment by AlexThiv** [comment]
@Ulthien Sorry that you're experiencing this issue. Is it possible that you didn't build the addressable packages for the assets?
Did you follow the steps in this section of the README https://github.com/oculus-samples/Unity-AssetStreaming#build
Let us know if after following the steps you have the same issues.
We are also in the process of updating our projects to newer version of the engine as well as our newer APKs, updates to come soon.
